version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-app
    container_name: nextjs-container
    restart: unless-stopped
    ports:
      - 3000:3000